=== dkwdp/dkwdp/schemas/level_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "next_level": {
      "anyOf": [
        {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "levelId": {
                  "type": "string"
                },
                "mapId": {
                  "type": "string"
                },
                "serverUrl": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "required": [
                "levelId"
              ],
              "additionalProperties": false
            },
            {
              "type": "string"
            }
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "elements": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "video"
              },
              "url": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": [
              "type",
              "url"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "text"
              },
              "markdown": {
                "type": "string"
              },
              "markdownFile": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "interactive"
              },
              "entrypoint": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "entrypoint"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "switch"
              },
              "next_levels": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "levelId": {
                      "anyOf": [
                        {
                          "anyOf": [
                            {
                              "type": "object",
                              "properties": {
                                "levelId": {
                                  "type": "string"
                                },
                                "mapId": {
                                  "type": "string"
                                },
                                "serverUrl": {
                                  "type": "string",
                                  "format": "uri"
                                }
                              },
                              "required": [
                                "levelId"
                              ],
                              "additionalProperties": false
                            },
                            {
                              "type": "string"
                            }
                          ]
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "image": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "levelId",
                    "image"
                  ],
                  "additionalProperties": false
                }
              }
            },
            "required": [
              "type",
              "next_levels"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "button"
              },
              "url": {
                "type": "string",
                "format": "uri"
              },
              "text": {
                "type": "string"
              },
              "target": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "url",
              "text"
            ],
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "required": [
    "id",
    "title",
    "next_level",
    "elements"
  ],
  "additionalProperties": false
}

=== dkwdp/dkwdp/static/content/map01/levels/intro/content.json
{
  "id": "intro",
  "title": "Level: Welcome Text",
  "next_level": "coordinate_systems",
  "elements": [
    {
      "type": "video",
      "url": "https://youtu.be/pDEb45Get2E?list=PLNpMof0wu8uQRZSwUCvoo6cxjm7mqUKkM"
    },
    {
      "type": "text",
      "markdownFile": "description.md"
    },
    {
      "type": "button",
      "text": "Start",
      "url": "https://scratch.mit.edu/projects/editor"
    }
  ]
}
